---
- hosts: web
  become: True
  gather_facts: no
  tasks:
    - name: Install python pip on RedHat family
      yum:
        name: python-pip
        state: present
      when: 
        ansible_os_family=="RedHat"
        
    - name: Install python pip on Debian family
      apt:
        name: python-pip
        state: present
      when: 
        ansible_os_family=="Debian"
        
    - name: Install docker on RedHat family
      yum:
        name: docker
        state: present
      when:
        ansible_os_family=="RedHat"
        
    - name: Install docker on Debian family
      apt:
        name: docker
        state: present
      when:
        ansible_os_family=="Debian"
        
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
        
    - name: Start the container
      docker_container:
        name: hariapp
        image: "srinivaskollipaka/myapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
