apiVersion: v1
kind: ReplicaSet
metadata: 
  name: pod1
  labels:
    app: sampleapp
    tire: front
spec:
  replicas: 2
  selector:
    matchLabels:
       tire: front
  template:
    metadata: 
      name: testpod
      labels:
        tire: front
    spec:
      containers:
      - name: test
        image: srinivaskollipaka/test-demo:1.0.1
        ports:
        - containerPort: 3000

---
apiVerion: v1
kind: Service
metadata: 
  name: testservice
  labels:
    tier: front
spec:
  type: NodePort
  ports: 
  - port: 3000
    nodePort: 32000
    protocol: TCP
    selector:
      tire: front
         
