---
- hosts: web
  become: True
  gather_facts: no
  tasks:
    - name: Install python pip 
      yum:
        name: python-pip:22.1.2
        state: present
        
    - name: Install docker
      yum:
        name: docker
        state: present
      
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: deocker-demo
        image: "srinivaskollipaka/demo-app:1.0.2"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
