- hosts: web
  become: yes
  user: test
  gather_facts: False
  tasks:
  - name: install docker
    yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
    loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

  - name: start and enable docker services
    service:
        name: docker
        state: started
        enabled: yes

  - name: Build image and with buildargs
    docker_image:
       path: srinivaskollipaka/myapp
       name: myapp
       buildargs:
         log_volume: /var/log/myapp
         listen_port: 5000

  - name: Tag and push to docker hub
    docker_image:
      name: myapp
      repository: srinivaskollipaka/myapp
      tag: 1.0
      push: yes
