- hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: install httpd
    yum: 
      name: httpd
      state: latest
  - name: enable and start nginx
    service:
      name: httpd
      state: started
      enabled: yes
  - name: copy index file to nginx path
    copy:
       src: /index.html
       dest: /var/www/html/
       mode: 0777
       owner: ec2-user
       group: ec2-user
