- hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: install nginx
    yum: 
      name: nginx
      state: latest
  - name: enable and start nginx
    service:
      name: nginx
      state: started
      enabled: yes
  - name: copy index file to nginx path
    copy:
       src: /index.html
       dest: /usr/share/nginx/html/
